"""empty message

Revision ID: cf07266678aa
Revises: 93a4f0c8297c
Create Date: 2020-02-12 18:02:22.045498

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cf07266678aa'
down_revision = '93a4f0c8297c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('img_url', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_task_img_url'), 'task', ['img_url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_img_url'), table_name='task')
    op.drop_column('task', 'img_url')
    # ### end Alembic commands ###
